### PR TITLE
[FIX, TST] Fix test paths

### PR DESCRIPTION
**Pull request by tsalo**
Closes None.

Changes proposed:
- Add badges to README and docs index page.
- Move tests. Alternatively, we could change the paths in the test config files.

### CODE REVIEW

**Comment by tsalo** [comment]
@tyarkoni One of the tests is failing because piston isn't installed. Would you prefer to add it to the test requirements or make it a general requirement?

**Comment by tyarkoni** [comment]
You mean PyStan? Let's add it to test requirements. It's only required if you want to use the Stan estimator, which most people probably won't. Would be good to have a `[all]` installation option though.

**Comment by tsalo** [comment]
@tyarkoni The SampleSizeEstimator test is failing, although I don't know why. Would you rather I just merge as-is and you could then fix the test in a later commit or should we fix it here?

FYI, GCC is also causing the container build to fail, so I chose to just skip the Stan-related tests for now.

**Comment by tyarkoni** [comment]
sorry @tsalo, just realized you were waiting on me. Yeah, let's merge as-is, if you don't mind resolving the conflict. The tests all pass for me now locally, so hopefully that failure was a blip that I've already fixed. If not, I'll take a look once it's running on CI.

**Comment by tsalo** [comment]
SampleSizeEstimator still failing, but merge conflict resolved. Merging now.

**Pull request merged**
