### PR TITLE
[WIP] Fixes to SampleSizeBasedLikelihoodEstimator

### PR DESCRIPTION
**Pull request by nicholst**
Various fixes to SampleSizeBasedLikelihoodEstimator... some maybe crucial.

### CODE REVIEW

**Comment by tyarkoni** [comment]
Thanks for the review, Tom! I'll have to think about the other changes, but the sign on the ML log-likelihood is definitely correct the way it was; the optimization is minimizing the return value, so it's expecting the negative LL. You can compare with the NLL for the `VarianceBasedLikelihoodEstimator`, which is verified to be correct (by comparison with metafor).

I think this is probably a good point to introduce a bunch of additional datasets to the tests that work from known (simulated) ground truth. I'll try to prioritize that in the next few days.

**Comment by tyarkoni** [comment]
On further inspection, the change from `n` to `1/n` was also unnecessary, because the weights are computed internally in the `WeightedLeastSquares` estimator by taking `1/v` (and `n` in this case is effectively passed as the `v`). I kept the other changes and opened a new PR, as I don't have push rights to your branch. Closing this one. Thanks!

**Comment by nicholst** [comment]
>  the sign on the ML log-likelihood is definitely correct the way it was; the optimization is minimizing the return value, so it's expecting the negative LL.

OK, but *negative* LL has positive signs.  I don't have a good link into a textbook, but checkout:

https://stats.stackexchange.com/questions/351549/maximum-likelihood-estimators-multivariate-gaussian

... showing the multivariate Gaussian *positive* log-likelihood having all the negative signs, just like you have, yet you are calling yours a "negative log-likelihood".

Do you see the issue?  If you've got a *negative* contribution of residual squared error then that is a thing that will need to be maximised, not minimised.

**Comment by tyarkoni** [comment]
Ah—I think the confusion here may be coming from the fact that in this code...
```python
w = 1. / (v + tau2)
R = y - X.dot(beta)
return -0.5 * (np.log(w).sum() - (R * w * R).sum())
```
...I'm taking the log of `1/(v + tau2)`, which is equivalent to `-np.log(v+tau2)`. So you're right that the sign of the returned value ends up being positive. But it's still the case that the previous expression was fine. :)

**Comment by nicholst** [comment]
Oh, sorry!  Yes, you're right! I was missing that w is inverse variance, and also missing the parens that make the interior minus sign a plus.

**Pull request closed without merging**
