### PR TITLE
[WIP] General improvements

### PR DESCRIPTION
**Pull request by tyarkoni**
Introduces many changes and improvements, including:
* A major refactor of the `effectsizes` module. Expressions are now loaded from JSON; the converter has been split up into separate `OneSampleEffectSizeConverter` and `TwoSampleEffectSizeConverter` classes; `to_dataset()` now takes a `measure` argument that indicates what the target output is (e.g., 'd', 'g', etc.); the semantics of `to_dataset()` roughly parallel metafor's `escalc()` (though support is much more limited); and various other minor changes.
* The `Dataset` class can now be initialized from a pandas `DataFrame`, with the other arguments being strings that specify which columns in the DF to use.
* All `Estimator` subclasses can now seamlessly handle 2d inputs, where the second dimension of `y` and `v` represents independent datasets (e.g., voxels). Some estimators (currently only the ones with closed-form solutions, i.e., `WeightedLeastSquares`, `DerSimonianLaird`, and `Hedges`) do vectorized computation throughout, so these are extremely fast even for very large arrays (e.g., arrays of dim `(10, 200000)` take << 1 second). @tsalo, I think this is pretty much stable, so once it's merged, I think we'll be in good shape to wrap pymare with NiMARE, at least for the closed-form estimators.
* The  `MetaRegressionResults` class has been completely rewritten. Key parameters are now accessible as attributes instead of having a master dictionary; the inverse covariance matrix is always passed in from estimators and stored; and most computed statistics are cached.

### CODE REVIEW

**Comment by nicholst** [comment]
Super!... A few questions...

I don't quite understand how, but I see that `to_dataset()` tracks the data, variance and sample size (`y`, `v`, & `n` in the return).  But if `m1` and `m2` are supplied separately, are they also passed through `to_dataset()` (same for `n1` and `n2`)?  Also, if meta-regression is supported, does the `X` come through here too?

Studying `expressions.json`, I'm confused by the distinction between Hedges's g and Cohen's d.  In some sources the distinction between the two is whether a simple average or weighted average of variances are used (e.g. on [NIST docs](https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/hedgeg.htm) and [Durlak, 2009](https://pubmed.ncbi.nlm.nih.gov/19223279/)), while other places make the distinction on the basis of whether the bias correction is applied ([Wikipedia](https://en.wikipedia.org/wiki/Effect_size#Cohen's_d))... in *any* event, they all pose it in terms of a two-sample statistic.  In `expressions.json` you have Hedges' g as being solely a one-sample statistic. Is there a reason why the two sample (seemingly default) Hedges's g was omitted?

**Comment by tyarkoni** [comment]
> I don't quite understand how, but I see that to_dataset() tracks the data, variance and sample size (y, v, & n in the return). But if m1 and m2 are supplied separately, are they also passed through to_dataset() (same for n1 and n2)?

No, none of the variables you feed into the effect size converter classes at initialization are carried through to the `Dataset` you get back if you call `to_dataset()`. But you don't *have* to call `to_dataset()`. The effect size converter classes can be used in one of two ways. If you call `get_{metric}()`, the class will try to give you back the measure you asked for if possible. E.g.:

```python
esc = OneSampleEffectSizeConverter(m=m, sd=sd)
esc.get_g()
```
The above gives you back an `NDArray` of Hedges' g, and nothing else.

Alternatively, if you call `to_dataset(metric='g')`, then it behaves like metafor's escalc, where you always get back `y` and `v`. I.e., `y` will be set to Hedges' g (and what you would get if you called `get_g()`) and `v` will be set to the variance of g (which you could also get by calling `get_v_g()`).

> Also, if meta-regression is supported, does the X come through here too?

Nope. You can think of the effect size converters and the meta-regression functionality as being completely independent. They're connected only by `to_dataset()`, which gives you back data in a form that can be fed directly to the master `meta_regression()` function, or to any `Estimator` class's `fit()` method. But `X` should never be passed to an `EffectSizeConverter` class, as it will just be ignored.

> Studying expressions.json, I'm confused by the distinction between Hedges's g and Cohen's d. In some sources the distinction between the two is whether a simple average or weighted average of variances are used (e.g. on NIST docs and Durlak, 2009), while other places make the distinction on the basis of whether the bias correction is applied (Wikipedia)...

I share your confusion. For the moment I went with the latter naming scheme (i.e., `g` is just `d` with the correction), but my current plan is to adapt most of metafor's escalc terminology, which is more explicit (e.g., "SMD" for standardized mean difference, and the computation appears to be identical to what I'm calling `'g'`). I'm open to suggestions though.

> in any event, they all pose it in terms of a two-sample statistic. In expressions.json you have Hedges' g as being solely a one-sample statistic. IsP there a reason why the two sample (seemingly default) Hedges's g was omitted?

It's actually in there; right at the top you have expressions with type `0`, which indicates that they should be used for both 1-sample and 2-sample cases. So this should work:

```python
esc = TwoSampleEffectSizeConverter(m1=m1, m2=m2, sd1=sd1, sd2=sd2)
esc.to_dataset(measure='g')
```

**Comment by tyarkoni** [comment]
BTW, I still haven't spent very much time on the expressions, so don't take this as anything close the final set. I'm planning to circle around to this in the next few days, but feel free to add suggestions in the meantime (and PRs are welcome of course).

**Comment by nicholst** [comment]
OK!  Thanks for clarifying independence of the independent variables (X) from the `to_dataset` structure, and also for explaining the role of `type` in `expressions.json`.

As for naming, I'm all for hewing to the notation used by metafor... it's widely used and, as far as I've reviewed it, I've always thought their notation was sensible.

**Pull request merged**
